services:
  vpn:
    image: qmcgaw/gluetun:v3.40.0
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./glueton:/glueton
    environment:
      VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}
      OPENVPN_USER: ${OPENVPN_USER}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      OPENVPN_REGIONS: ${OPENVPN_REGIONS}
    # ports:
    #   - 127.0.0.1:5080:5080
    restart: unless-stopped
    labels:
      com.centrylinklabs.watchtower.enable: true

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:5.0.3
    depends_on:
      vpn:
        condition: service_healthy
    network_mode: service:vpn
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      WEBUI_PORT: 5080
    volumes:
      - ./qbittorrent/config:/config
      - ./qbittorrent/vuetorrent:/vuetorrent
      - /mnt/data/torrents:/downloads
    restart: unless-stopped
    labels:
      homepage.group: Downloaders
      homepage.name: qBittorrent
      homepage.icon: qbittorrent
      homepage.href: https://media.doubleoh13.dev/qbittorrent
      homepage.widget.type: qbittorrent
      homepage.widget.url: http://vpn:5080
      homepage.widget.username: ${QBITTORRENT_USERNAME}
      homepage.widget.password: ${QBITTORRENT_PASSWORD}
      com.centrylinklabs.watchtower.enable: true

  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      VERSION: docker
    volumes:
      - ./plex/config:/config
      - /mnt/data/media/movies:/movies
      - /mnt/data/media/tv:/tv
    restart: unless-stopped
    labels:
      homepage.group: Media
      homepage.name: Plex
      homepage.icon: plex
      homepage.href: https://plex.doubleoh13.dev
      homepage.widget.type: plex
      homepage.widget.url: http://10.13.0.30:32400
      homepage.widget.key: ${PLEX_KEY}
      com.centrylinklabs.watchtower.enable: true

  overseerr:
    container_name: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/New_York
    volumes:
      - ./overseerr/config:/config
    # ports:
    #   - 127.0.0.1:5055:5055
    restart: unless-stopped
    labels:
      homepage.group: Media
      homepage.name: Overseerr
      homepage.icon: overseerr
      homepage.href: https://overseerr.doubleoh13.dev
      homepage.widget.type: overseerr
      homepage.widget.url: http://overseerr:5055
      homepage.widget.key: ${OVERSEERR_KEY}
      com.centrylinklabs.watchtower.enable: true

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    labels:
      com.centrylinklabs.watchtower.enable: true

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - ./prowlarr/config:/config
    # ports:
    #   - 127.0.0.1:9696:9696
    restart: unless-stopped
    labels:
      homepage.group: Media
      homepage.name: Prowlarr
      homepage.icon: prowlarr
      homepage.href: https://media.doubleoh13.dev/prowlarr
      homepage.widget.type: prowlarr
      homepage.widget.url: http://prowlarr:9696
      homepage.widget.key: ${PROWLARR_KEY}
      com.centrylinklabs.watchtower.enable: true

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - ./sonarr/config:/config
      - /mnt/data/media/tv:/tv
      - /mnt/data/torrents:/downloads
    restart: unless-stopped
    labels:
      homepage.group: Media
      homepage.name: Sonarr
      homepage.icon: sonarr
      homepage.href: https://media.doubleoh13.dev/sonarr
      homepage.widget.type: sonarr
      homepage.widget.url: http://sonarr:8989
      homepage.widget.key: ${SONARR_KEY}
      com.centrylinklabs.watchtower.enable: true

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      - ./radarr/config:/config
      - /mnt/data/media/movies:/movies
      - /mnt/data/torrents:/downloads
    # ports:
    #   - 127.0.0.1:7878:7878
    restart: unless-stopped
    labels:
      homepage.group: Media
      homepage.name: Radarr
      homepage.icon: radarr
      homepage.href: https://media.doubleoh13.dev/radarr
      homepage.widget.type: radarr
      homepage.widget.url: http://radarr:7878
      homepage.widget.key: ${RADARR_KEY}
      com.centrylinklabs.watchtower.enable: true

networks:
  default:
    name: media-network
    external: true
